updoots_web:
  build: .
  links:
    - updoots_db
  ports:
    - "3000:3000"
  volumes:
    - .:/app/src/github.com/domtheporcupine/updoots
updoots_db:
  image: mysql
  environment:
    MYSQL_PASSWORD: npassword
    MYSQL_USER: nuser
    MYSQL_ROOT_PASSWORD: npassword
  ports:
    - "3306:3306"
adminer:
  image: adminer
  ports:
    - "4500:8080"
  links:
    - updoots_db
    