pittyak_web:
  build: .
  links:
    - pittyak_db
  ports:
    - "3000:3000"
  volumes:
    - .:/app/src/github.com/domtheporcupine/pittchat
pittyak_db:
  image: mysql
  environment:
    MYSQL_PASSWORD: npassword
    MYSQL_USER: nuser
    MYSQL_ROOT_PASSWORD: npassword
  ports:
    - "3306:3306"