updoots_web:
  build: .
  links:
    - updoots_db
  ports:
    - "3000:3001"
  volumes:
    - .:/app/src/github.com/domtheporcupine/updoots
updoots_db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: npassword
    POSTGRES_USER: nuser
    POSTGRES_ROOT_PASSWORD: npassword
  ports:
    - "5432:5432"
  volumes:
    - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
adminer:
  image: adminer
  ports:
    - "4500:8080"
  links:
    - updoots_db
    